# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ewtzD1z20MScunr4Yyrpm4BusSoUxD5U
"""

!pip install streamlit

import streamlit as st
import numpy as np
import json
import re
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.text import tokenizer_from_json
from tensorflow.keras.preprocessing.sequence import pad_sequences

# =====================================
# KONFIGURASI HALAMAN
# =====================================
st.set_page_config(
    page_title="Analisis Sentimen LSTM",
    page_icon="🎀",
    layout="centered"
)

# =====================================
# CUSTOM CSS (PINK GEMOY)
# =====================================
st.markdown("""
<style>

/* Background utama */
.stApp {
    background: linear-gradient(
        135deg,
        #ffe6f2 0%,
        #ffd9ec 50%,
        #fff2f8 100%
    );
}

/* Judul */
.main-title {
    text-align: center;
    color: #ff4fa3;
    font-size: 42px;
    font-weight: bold;
    margin-bottom: 5px;
}

/* Subtitle */
.subtitle {
    text-align: center;
    color: #ff7eb6;
    font-size: 18px;
    margin-bottom: 25px;
}

/* Card utama */
.main-card {
    background: white;
    padding: 25px;
    border-radius: 25px;
    box-shadow: 0px 4px 20px rgba(255,105,180,0.15);
}

/* Text Area */
textarea {
    border-radius: 15px !important;
    border: 2px solid #ffb6d9 !important;
}

/* Tombol */
.stButton > button {
    width: 100%;
    background: linear-gradient(
        90deg,
        #ff69b4,
        #ff85c1
    );
    color: white;
    border: none;
    border-radius: 15px;
    font-size: 18px;
    font-weight: bold;
    padding: 10px;
    transition: 0.3s;
}

.stButton > button:hover {
    transform: scale(1.03);
    background: linear-gradient(
        90deg,
        #ff4fa3,
        #ff69b4
    );
}

/* Sidebar */
section[data-testid="stSidebar"] {
    background-color: #ffe0ef;
}

/* Footer */
.footer {
    margin-top: 50px;
    text-align: center;
    color: #c05a8c;
    font-size: 14px;
    padding: 15px;
}

/* Success */
.stSuccess {
    border-radius: 15px;
}

/* Error */
.stError {
    border-radius: 15px;
}

/* Warning */
.stWarning {
    border-radius: 15px;
}

</style>
""", unsafe_allow_html=True)

# =====================================
# LOAD MODEL & TOKENIZER
# =====================================
@st.cache_resource
def load_sentiment_artifacts():
    model = load_model('lstm_model.h5')

    with open('tokenizer.json') as f:
        data = json.load(f)
        tokenizer = tokenizer_from_json(data)

    return model, tokenizer

try:
    model, tokenizer = load_sentiment_artifacts()
    model_loaded = True
except Exception as e:
    model_loaded = False
    st.error(
        f"Gagal memuat model atau tokenizer.\n\nError: {e}"
    )

# =====================================
# HEADER
# =====================================
st.markdown(
    "<div class='main-title'>🎀 Analisis Sentimen Teks 🎀</div>",
    unsafe_allow_html=True
)

st.markdown(
    """
    <div class='subtitle'>
    💖 Klasifikasi Sentimen Positif dan Negatif menggunakan LSTM 💖
    </div>
    """,
    unsafe_allow_html=True
)

# =====================================
# CARD UTAMA
# =====================================
st.markdown("<div class='main-card'>", unsafe_allow_html=True)

st.write(
    """
    Masukkan ulasan atau kalimat yang ingin dianalisis.

    Model akan memprediksi apakah sentimen teks tersebut
    termasuk **POSITIF** atau **NEGATIF**.
    """
)

user_input = st.text_area(
    "📝 Input Teks / Ulasan",
    placeholder="Contoh: Barangnya bagus banget, pengirimannya cepat dan rapi..."
)

if st.button("✨ Analisis Sentimen"):

    if not model_loaded:
        st.warning("Model belum siap digunakan.")

    elif user_input.strip() == "":
        st.warning("Silakan masukkan teks terlebih dahulu.")

    else:

        # =====================================
        # PREPROCESSING
        # =====================================
        text_clean = user_input.lower()
        text_clean = re.sub(r'[^a-zA-Z\s]', '', text_clean)
        text_clean = re.sub(r'\s+', ' ', text_clean).strip()

        # =====================================
        # TOKENIZATION
        # =====================================
        sequences = tokenizer.texts_to_sequences([text_clean])

        padded = pad_sequences(
            sequences,
            maxlen=35,
            padding='post',
            truncating='post'
        )

        # =====================================
        # PREDIKSI
        # =====================================
        prediction = model.predict(padded, verbose=0)[0][0]

        st.write("---")
        st.subheader("📊 Hasil Analisis")

        if prediction >= 0.5:

            st.success(
                f"""
                🎉 **SENTIMEN POSITIF**

                Tingkat Keyakinan Model:
                **{prediction:.2%}**
                """
            )

        else:

            st.error(
                f"""
                😔 **SENTIMEN NEGATIF**

                Tingkat Keyakinan Model:
                **{(1-prediction):.2%}**
                """
            )

st.markdown("</div>", unsafe_allow_html=True)

# =====================================
# SIDEBAR
# =====================================
st.sidebar.markdown("## 🎀 Informasi Model")

st.sidebar.markdown("""
💗 **Algoritma:** LSTM

💗 **Framework:** TensorFlow / Keras

💗 **Deployment:** Streamlit

💗 **Input:** Teks Bahasa Indonesia

💗 **Output:** Positif atau Negatif

💗 **Padding Sequence:** 35 kata
""")

# =====================================
# FOOTER
# =====================================
st.markdown(
    """
    <div class="footer">
        <hr>
        🎓 <b>Tugas Mata Kuliah Text Mining</b><br>
        Nama: <b>Zahra Annisa</b><br>
        NIM: <b>2702284086</b>
    </div>
    """,
    unsafe_allow_html=True
)